project:
  type: website
  render:
    - glp_guide_v2.qmd
  resources:
    - recommendations.js
    - data/**

format:
  html:
    theme:
      - default
      - styles.scss
    toc: false
    smooth-scroll: true
    page-layout: full
    title-block: false
    anchor-sections: false